tenis_chile/urls.py
from tenis_chile.views import PlayerListView
from django.urls import path
from . import views

urlpatterns = [
    path("jugadores/", views.PlayerListView.as_view(), name="players-list"),
    path("jugadores/<slug:slug>",
         views.PlayerDetailView.as_view(), name="player-detail"),
    path("", views.IndexView.as_view(), name="index"),
    path("torneos/<int:pk>", views.TournamentDetail.as_view(),
         name="tournament-detail"),
    path("partidos/<int:pk>", views.TournamentMatchDetail.as_view(),
         name="tournament-match-detail")

]

tenis_chile_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tenis_chile.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tenis_chile/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django_resized import ResizedImageField
import re
from datetime import date


class Player(models.Model):
    FOREHAND_1 = 'RF'
    FOREHAND_2 = 'LF'
    U_FOREHAND = 'UF'
    BACKHAND_1 = 'R2'
    BACKHAND_2 = 'R1'
    U_BACKHAND = 'UB'
    FOREHAND_CHOICES = [
        (FOREHAND_1, 'Diestro'),
        (FOREHAND_2, 'Zurdo'),
        (U_FOREHAND, 'Desconocido'),
    ]
    BACKHAND_CHOICES = [
        (BACKHAND_1, 'Revés a dos manos'),
        (BACKHAND_2, 'Revés a una mano'),
        (U_BACKHAND, 'Desconocido'),
    ]
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    image = ResizedImageField(size=[200, 200], upload_to='uploads', null=True)
    birth_date = models.DateField()
    nationality = models.CharField(max_length=50, default='Chile')
    weight = models.IntegerField(blank=True, null=True)  # in kg
    height = models.IntegerField(blank=True, null=True)  # in cm
    # blank allow empty strings in form
    coach = models.CharField(max_length=100, blank=True)
    birth_place = models.CharField(max_length=50, blank=True)
    residence = models.CharField(max_length=50, blank=True)
    actual_ranking = models.IntegerField(
        null=True, validators=[MinValueValidator(0)])
    pro_titles = models.IntegerField(
        blank=True, null=True, validators=[MinValueValidator(0)])
    bio = models.TextField(blank=True)
    sponsor = models.CharField(blank=True, max_length=50)
    racket = models.CharField(blank=True, max_length=50)
    actual_points = models.IntegerField(
        null=True, validators=[MinValueValidator(0)])
    forehand = models.CharField(
        blank=True, max_length=2, choices=FOREHAND_CHOICES)
    backhand = models.CharField(
        blank=True, max_length=2, choices=BACKHAND_CHOICES)
    slug = models.SlugField(null=True)

    def __str__(self):
        return self.get_full_name()

    def get_full_name(self):
        return f'{self.first_name} {self.last_name}'

    def get_age(self):
        today = date.today()
        born = self.birth_date
        return today.year - born.year - ((today.month, today.day) < (born.month, born.day))


class RankingHistory(models.Model):
    player = models.ForeignKey(
        Player, on_delete=models.CASCADE, related_name='rankings')
    date = models.DateField()
    ranking = models.IntegerField(validators=[MinValueValidator(0)])
    points = models.IntegerField(
        null=True, blank=True, validators=[MinValueValidator(0)])


class TournamentType(models.Model):
    name = models.CharField(max_length=50)
    image = ResizedImageField(
        size=[200, 200], upload_to='uploads/tournament_types', null=True)
    level = models.CharField(max_length=50)
    points = models.IntegerField(validators=[MinValueValidator(0)])
    association = models.CharField(max_length=50)
    # prize = models.IntegerField(validators=[MinValueValidator(0)]) # dollars

    def __str__(self):
        return self.name


class Tournament(models.Model):
    CLAY = 'C'
    HARD = 'H'
    GRASS = 'G'
    CARPET = 'P'
    SURFACE_CHOICES = [
        (CLAY, 'Arcilla'),
        (HARD, 'Cancha rápida'),
        (GRASS, 'Pasto'),
        (CARPET, 'Carpeta')
    ]
    name = models.CharField(max_length=50)
    image = ResizedImageField(
        size=[200, 200], upload_to='uploads/tournaments', null=True)
    date = models.DateField()
    surface = models.CharField(max_length=1, choices=SURFACE_CHOICES)
    players = models.ManyToManyField(Player, related_name='tournaments')
    tournament_type = models.OneToOneField(
        TournamentType, on_delete=models.CASCADE)
    location = models.CharField(max_length=50)
    rounds = models.IntegerField(null=True, validators=[MinValueValidator(1)])
    prize = models.IntegerField(null=True, validators=[
                                MinValueValidator(0)])  # dollars

    def __str__(self):
        return self.name


class TournamentMatch(models.Model):
    LOCAL = '1'
    AWAY = '2'
    NOT_PLAYED = 'X'
    WINNER_CHOICES = [
        (LOCAL, 'Dupla 1'),
        (AWAY, 'Dupla 2'),
        (NOT_PLAYED, 'No jugado'),
    ]
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
    players = models.ManyToManyField(Player, null=True, related_name='+')
    date = models.DateField()
    isLive = models.BooleanField()
    set_1 = models.CharField(max_length=8)
    set_2 = models.CharField(max_length=8)
    set_3 = models.CharField(max_length=8, blank=True)
    set_4 = models.CharField(max_length=8, blank=True)
    set_5 = models.CharField(max_length=8, blank=True)
    winners = models.ManyToManyField(
        Player, blank=True, null=True, related_name='+')
    round_number = models.IntegerField(validators=[MinValueValidator(1)])
    highlights_embed = models.CharField(max_length=300, blank=True, null=True)
    streaming_embed = models.TextField(blank=True, null=True)

    def get_winners(self):
        winners = self.winners.all()
        lst = []
        for winner in winners:
            lst.append(winner.get_full_name())
        return ' - '.join(lst)

tenis_chile/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.base import TemplateView

from . import models
# Create your views here.


class PlayerListView(ListView):
    template_name = "tenis_chile/players_list.html"
    model = models.Player
    context_object_name = 'players'

    def get_queryset(self):
        return models.Player.objects.filter(nationality='Chile')


class PlayerDetailView(DetailView):
    template_name = "tenis_chile/player_detail.html"
    model = models.Player
    context_object_name = 'player'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        player = models.Player.objects.get(slug=self.kwargs['slug'])
        context['ranking_history'] = player.rankings.all().order_by('-date')
        context['matches'] = models.TournamentMatch.objects.filter(
            players__id__exact=player.id).order_by('-date')
        return context


class IndexView(TemplateView):
    template_name = "tenis_chile/index.html"


class TournamentDetail(DetailView):
    template_name = "tenis_chile/tournament_detail.html"
    model = models.Tournament
    context_object_name = 'tournament'


class TournamentMatchDetail(DetailView):
    template_name = "tenis_chile/tournament_match_detail.html"
    model = models.TournamentMatch
    context_object_name = 'match'

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block page_title %}{% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" 
        rel="stylesheet" 
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" 
        crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  {% block css_file %} {% endblock %}
</head>

<body>
  <nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Inicio</a>
      {# Responsive Menu Button #}
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {# Responsive Collapsable Content #}
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'players-list' %}">Jugadores</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  {% block page_body %}{% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
          crossorigin="anonymous"></script>
</body>

</html>

tenis_chile/templates/tenis_chile/index.html
{% extends 'base.html' %}


{% block page_title %}
Inicio
{% endblock %}

{% block page_body %}

{% endblock %}

tenis_chile/templates/tenis_chile/player_detail.html
{% extends 'base.html' %} 
{% block page_title %} 
  Todos los jugadores {% endblock %} 
{% block page_body %}
<div class="container-fluid-lg">
  <div class="row justify-content-md-center">
    <div class="col col-offset-2 col-lg-9 mt-5">
      <h3>Datos de jugador</h3>
      <div class="card mb-3" style="max-width: 1000px">
        <div class="row g-0">
          {# Image #}
          <div class="col-md-4 text-center mt-2">
            <img src="{{player.image.url}}" alt="..." />
          </div>
          {# Data #}
          <div class="col-md-4">
            <div class="card-body">
              <h5 class="card-title">{{ player.get_full_name }}</h5>
              <h6 class="card-subtitle mb-2 text-muted">
                Edad: {{ player.get_age }}
              </h6>
              <h6 class="card-subtitle mb-2 text-muted">
                Ranking: {{ player.actual_ranking }}
              </h6>
              <h6 class="card-subtitle mb-2 text-muted">
                Títulos ATP: {{player.pro_titles}}
              </h6>
              <p class="card-text">
                <small class="text-muted">Entrenador: {{ player.coach }}</small>
              </p>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card-body">
              <h6 class="card-subtitle mb-2 mt-4 text-muted">
                Peso: {{ player.weight }} kg
              </h6>
              <h6 class="card-subtitle mb-2 text-muted">
                Altura: {{ player.height }} cm
              </h6>
              <h6 class="card-subtitle mb-2 text-muted">
                Lugar de Nacimiento: {{ player.birth_place }}
              </h6>
              <p class="card-text">
                <small class="text-muted">Raqueta: {{ player.racket }}</small>
              </p>
            </div>
          </div>
          {# Bio #}
          <div class="card-footer">
            <div class="accordion" id="accordionBio">
              <div class="accordion-item">
                <h2 class="accordion-header" id="headingBio">
                  <button
                    class="accordion-button collapsed"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#collapseBio"
                    aria-expanded="false"
                    aria-controls="collapseBio"
                  >
                    Bio
                  </button>
                </h2>
                <div
                  id="collapseBio"
                  class="accordion-collapse collapse"
                  aria-labelledby="headingBio"
                  data-bs-parent="#accordionBio"
                >
                  <div class="accordion-body">
                    <p class="card-text">{{ player.bio|linebreaks }}</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <h3>Últimos Partidos</h3>
      <div class="card mb-3" style="max-width: 1000px">
        <div class="row g-0">
          {# Data #}
          <div class="col col-offset-4">
            <div class="card-body">
              <h6 class="card-subtitle mb-2 text-muted">
                Partidos disputados últimamente
              </h6>
              <table class="table text-center">
                <thead>
                  <tr>
                    <th scope="col"></th>
                    <th scope="col">Fecha</th>
                    <th scope="col">Torneo</th>
                    <th scope="col">Ganador</th>
                    <th scope="col">Resultado</th>
                  </tr>
                </thead>
                <tbody>
                  {% for match in matches %}
                  <tr>
                    <td>
                      <a href="{% url 'tournament-match-detail' match.id %}"
                        >Ver</a
                      >
                    </td>
                    <td>{{ match.date }}</td>
                    <td>
                      <a
                        href="{% url 'tournament-detail' match.tournament.id %}"
                        >{{ match.tournament.name }}</a
                      >
                    </td>
                    <td>
                      {% for p in match.players.all %} 
                        {% if p.get_full_name != player.get_full_name %}
                          {{ p.get_full_name }}
                        {% endif %} 
                        {% endfor %}
                    </td>
                    {% for winner in match.winners.all %} 
                      {% if winner.get_full_name == player.get_full_name %}
                      <td>Victoria</td>
                      {% else %}
                      <td>Derrota</td>
                      {% endif %} 
                    {% endfor %}
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>

      <h3>Historial Ranking</h3>
      <div class="card mb-3" style="max-width: 1000px">
        <div class="row g-0">
          {# Data #}
          <div class="col col-offset-4">
            <div class="card-body">
              <h6 class="card-subtitle mb-2 text-muted">
                Ranking al término de cada año
              </h6>
              <table class="table text-center">
                <thead>
                  <tr>
                    <th scope="col">Año</th>
                    <th scope="col">Ranking</th>
                  </tr>
                </thead>
                <tbody>
                  {% for ranking in ranking_history %}
                  <tr>
                    <td>{{ ranking.date|date:'Y' }}</td>
                    <td>{{ ranking.ranking }}</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

tenis_chile/templates/tenis_chile/players_list.html
{% extends 'base.html' %} 
{% load static %} 
{% block page_title %} 
  Jugadores 
{% endblock %} {% block css_file %}
<link rel="stylesheet" href="{% static 'css/player_list.css' %}" />
{% endblock %} {% block page_body %}
<div class="container-fluid-lg">
  <div class="row justify-content-md-center">
    <div class="col col-offset-2 col-lg-9 mt-5">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Nombre</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          {% for player in players %}
          <tr>
            <td>{{player.get_full_name}}</td>
            <td>
              <a href="{% url 'player-detail' player.slug %}">Ver detalles</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

tenis_chile/templates/tenis_chile/tournament_detail.html
{% extends 'base.html' %} 
{% block page_title %} 
  Detalle Torneo 
{% endblock %}
{% block page_body %}
<div class="container-fluid-lg">
  <div class="row justify-content-md-center">
    <div class="col col-offset-2 col-lg-9 mt-5">
      <h3>Datos de Torneo</h3>
      {# Card #}
      <div class="card mb-3" style="max-width: 1000px">
        <div class="row g-0">
          {# Image #}
          <div class="col-md-4 text-center mt-4">
            <img src="{{tournament.image.url}}" alt="..." />
          </div>
          {# Data #}
          <div class="col-md-4">
            <div class="card-body">
              <h5 class="card-title">{{ tournament.name }}</h5>
              <h6 class="card-subtitle mb-2 text-muted">
                Lugar: {{ tournament.location }}
              </h6>
              <h6 class="card-subtitle mb-2 text-muted">
                Superficie: {{ tournament.surface }}
              </h6>
              <h6 class="card-subtitle mb-2 text-muted">
                Tipo de Torneo: {{ tournament.tournament_type.name }}
              </h6>
              <p class="card-text">
                <small class="text-muted"
                  >Premio: $USD {{ tournament.prize }}</small
                >
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

tenis_chile/templates/tenis_chile/tournament_match_detail.html
{% extends 'base.html' %} 
{% load static %} 
{% block page_title %} 
  Detalle Torneo 
{% endblock %} 
{% block css_file %}
<link rel="stylesheet" href="{% static 'css/tournament_match_detail.css' %}" />
{% endblock %} {% block page_body %}
<div class="container-fluid-lg">
  <div class="row justify-content-md-center">
    <div class="col col-offset-2 col-lg-9 mt-5">
      <h3>Datos de Partido {%if match.isLive %} ¡EN VIVO! {% endif %}</h3>
      {# Card #}
      <div class="card mb-3" style="max-width: 1000px">
        <div class="row g-0">
          {# Data #}
          <div class="col-md-4">
            <div class="card-body">
              <h5 class="card-title">Torneo: {{ match.tournament.name  }}</h5>
              <h6 class="card-subtitle mb-2 text-muted">
                Fecha: {{match.date}}
              </h6>
              <h6 class="card-subtitle mb-2 text-muted">
                {% if match.winners.all %} Ganador {% endif %}
                {{ match.get_winners }} {{ match.set_1 }} {{ match.set_2 }} {{match.set_3 }} {{ match.set_4 }} {{ match.set_5 }}
              </h6>
            </div>
          </div>
        </div>
      </div>

      <h3>Jugadores</h3>
      <div class="card mb-3" style="max-width: 1000px">
        {% for player in match.players.all %}
        <div class="row g-0">
          {# Image #}
          <div class="col-md-4 text-center mt-2">
            <img src="{{player.image.url}}" alt="..." />
          </div>
          {# Data #}
          <div class="col-md-4">
            <div class="card-body">
              <h5 class="card-title">{{ player.get_full_name }}</h5>
              <h6 class="card-subtitle mb-2 text-muted">
                Edad: {{ player.get_age }}
              </h6>
              <h6 class="card-subtitle mb-2 text-muted">
                Ranking: {{ player.actual_ranking }}
              </h6>
              <h6 class="card-subtitle mb-2 text-muted">
                Títulos ATP: {{ player.pro_titles }}
              </h6>
              <p class="card-text">
                <small class="text-muted">Entrenador: {{ player.coach }}</small>
              </p>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>

      {% if match.highlights_embed %}
      <h3>Video</h3>
      <div class="card mb-3" style="max-width: 1000px">
        <div class="row g-0">
          <div class="col-md-4">
            <div class="card-body">{{ match.highlights_embed | safe }}</div>
          </div>
        </div>
      </div>
      {% endif %} {% if match.streaming_embed %}
      <h3>Streaming</h3>
      <div class="card mb-3" style="max-width: 1000px">
        <div class="row g-0">
          <div class="col-md-4">
            <div class="card-body">{{ match.streaming_embed | safe }}</div>
          </div>
        </div>
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}